# Generated by Django 3.0.1 on 2020-02-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup',
            name='address1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='address2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='date_of_issue',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='dob',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='expiringdate',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='fullname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='middlename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='passid',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='zipcode',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
