# Generated by Django 2.2 on 2020-02-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20200212_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_signup',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='date_of_issue',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='expiringdate',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='passid',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='region',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='zipcode',
        ),
    ]
