# Generated by Django 2.2 on 2020-02-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20200213_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=200)),
                ('fullname', models.CharField(default='', max_length=255)),
                ('middlename', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('address1', models.CharField(default='', max_length=255)),
                ('address2', models.CharField(default='', max_length=255)),
                ('zipcode', models.PositiveSmallIntegerField(default=0)),
                ('city', models.CharField(default='', max_length=255)),
                ('region', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('dob', models.PositiveSmallIntegerField(default=0)),
                ('passid', models.PositiveSmallIntegerField(default=0)),
                ('date_of_issue', models.PositiveSmallIntegerField(default=0)),
                ('expiringdate', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
