# Generated by Django 2.2 on 2020-02-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_verification_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='image1',
            new_name='passportimg',
        ),
    ]
