# Generated by Django 2.2 on 2020-02-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20200214_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='selfieimg',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
