# Generated by Django 2.2 on 2020-02-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_verification_documentwithaddimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup',
            name='profileimg',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
