# Generated by Django 2.2 on 2020-02-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_user_signup_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='profileimg',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
