# Generated by Django 3.0.3 on 2020-02-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_auto_20200220_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='transictions',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tuser_id', models.CharField(max_length=200)),
                ('tamout', models.IntegerField(default=0)),
                ('token', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.statuses')),
            ],
        ),
    ]
